package com.sjunejo.what2say.sqlite;

/**
 * Contains the default topics that initially populate the SQLite database.
 * @author Sadruddin Junejo
 *
 */
public class InitialData {
	
	public static final String[] DEFAULT_TOPICS = {
		"Heard any good music lately?",
		"Do you play or follow any sports?",
		"What do you do in your spare time?", 
		"What do you do for a living?",
		"Seen any good films recently?",
		"Hey, have you seen <<insert tv show or film here>>",
		"Talk about your surroundings!",
		"How do you know <<party host>>?",
		"Do you have any siblings?",
		"Where did you grow up?",
		"Where did you go on your last vacation? Did you like it?",
		"What was the best vacation/trip you've been on?",
		"What's the worst restaurant experience you've ever had?",
		"When you were a kid, what did you want to be when you grew up?",
		"Talk about a mutual acquaintance!",
		"How did you get involved in this event?",
		"Talk about current affairs!",
		"What's your favourite dino type?",
		"How about the game last night!",
		"What'd you get up to earlier today?",
		"Can you help me open this bottle? (note: must have bottle)",
		"Tell a funny joke!",
		"Tell a funny anecdote!",
		"Last time we talked, you were...<insert circumstance here> What happened?",
		"How's your job coming along?",
		"Crazy weather we've been having, huh?",
		"Have you been here before?",
		"Did you have to travel far to get here?",
		"So what do you usually get up to on weekends?",
		"Do you like to cook?",
		"I like pickles. Do you like pickles?",
		"Nice accent, where did you get it from?",
		"You much of a gamer?",
		"What video game consoles do you own?",
		"Have I met you somewhere before? (lol)",
		"What was the first time you broke the law?",
		"What was your worst date ever?",
		"What's your favourite food?",
		"What's the best gift you ever got from someone?",
		"What's the best gift you ever gave?",
		"What's your most embarrassing moment?",
		"Your idea of a perfect night out?",
		"Five things you can't live without?",
		"What are your favourite books?",
		"Read a good book recently?",
		"So I read a good book the other day...",
		"Do you believe in fate?",
		"Favourite toy as a child?",
		"Future honeymoon destination?",
		"Most memorable birthday?",
		"Oddest job you ever had?",
		"What was the last time you lost your temper?",
		"Are you a cat or dog person?",
		"If you wrote a book, what would it be about?",
		"What was your first concert?",
		"What was your first job?",
		"Most famous person you've met?",
		"What's your favourite midnight snack?",
		"Worst purchase you ever made?",
		"What would you do if you won the lottery?",
		"What gets you excited in life?",
		"Are you a cat or dog person?",
		"What's the most embarrassing CD you have in your collection?",
		"Are you a reddit user?",
		"What's the one movie you watch over and over?",
		"Talk in an accent you'd like to have?",
		"What's the worst movie you've seen?",
		"What do you want more of?",
		"What would be your ideal sandwich?",
		"What's your secret talent that you're willing to reveal?",
		"Would you rather be able to fly, be invisible or read minds? Why?",
		"What one food and beverage would you choose for a desert island and why?",
		"What was your biggest surprise ever?",
		"What was your favourite toy as a child?",
		"What was the greatest invention, ever?",
		"Need another drink?",
		"Do you have a special place to go to?",
		"Describe yourself using 5 words.",
		"Who is the most important person in the world to you?",
		"What are three doings you've never done, but would like to try?",
		"Where are your parents from?",
		"Did you go to college/university? What did you major in?",
		"Do you have any nephews or nieces?",
		"Are you a nature person? Do you like outdoorsy stuff?",
		"Do you believe in star signs and astrology?",
		"Can you name something quirky about yourself?",
		"Are there any good bars or clubs around?",
		"Any good restaurants around here?",
		"Any good shops around here?",
		"If you could go back in time, which time period would you travel to?",
		"What level of school was your preferred one?",
		"What books have you read more than once?",
		"What's your opinion on reality TV shows?",
		"Where were you on 9/11?",
		"What's the longest you've gone without sleep?",
		"Are you afraid of heights?",
		"What's your favourite knock knock joke?",
		"What's the longest you've ever waited in a queue?",
		"Are there any songs you know all the lyrics too?",
		"Seen any good Youtube videos lately?",
		"Do you use Facebook?",
		"Do you use Google+?",
		"Do you use Twitter?",
		"Is your life going the way you want it to at the moment?",
		"What are your biggest pet peeves?",
		"What was your favourite cartoon as a kid?",
		"Who was your first pop star/celebrity crush?",
		"Have you ever done volunteer work?",
		"Have you ever fallen in love at first sight?",
		"Have you ever dyed your hair blond?",
		"Have you ever been to a music festival?",
		"So what are your plans for the future?",
		"What phone do you have?",
		"Who is the most interesting person you have ever met?",
		"Who's had the biggest influence on your life?",
		"If you were God for a day, what would you do?",
		"If you could be the parent of a famous person, who would it be and why?",
		"How would you spend your ideal day?",
		"What, if anything, is too serious to be joked about?",
		"What is your idea of a perfect romantic evening?",
		"If you saw someone shoplifting, what would you do?",
		"Who would you choose to be shipwrecked on a deserted island with?",
		"What's worse: having expectations that are too high, or no expectations?",
		"How do you know when you're in love?",
		"If you could be invisible for a day, what would you do?",
		"What's the last album you listened to all the way through?",
		"What character from films/literature would you most like as a best friend?",
		"If you were to throw a theme party, what theme would you choose?",
		"If you had an unlimited budget to throw your own party, what would it be like?",
		"If you could invite three celebrities to a party who would they be?",
		"What's your dream job?",
		"Comment on that person's/other people's dresses/clothing.",
		"Come up with an excuse and get out of there quick.",
		"Explain why Homer Simpson should be the next president!",
		"The biggest lies government tell us!",
		"Daydreaming should be a religion.",
		"Is there anyone you share a bromance with?",
		"Suggest a game to play.",
		"Suggest a drinking game!",
		"If you could invent something that would make life easier, what would it be?",
		"What's one thing you learnt this week that you didn't know before?",
		"What quality or condition would you like to have in your life that you don't currently have?",
		"If you could do anything in the world without a chance of failure, what would you do?",
		"Would you be willing to go to a one-way trip to Mars to live with a small colony of humans?",
		"Do you know Shinigami like apples?",
		"What is the meaning of life to you?",
		"I wish I could stay longer; this party's getting better and better.",
		"Suggest a food for the other person/people to try.",
		"Do you know any good icebreakers?",
		"Well, this is awkward...",
		"Do you study anything at the moment?",
		"Have you been to any similiar events?",
		"If you were asked to do so, would you sing in public?",
		"What's the craziest thing you've ever done?",
		"If you were throwing a party for five people, who would you invite?",
		"If time and money were no object, to what causes would you dedicate your efforts?",
		"What is your favourite comfort food meal?",
		"What's the coolest thing you've ever bought on eBay?",
		"If your best friend had 3 words to describe you, what would they be?",
		"Most embarrassing moment in high school?",
		"Worst game you've played?",
		"Peanut butter. Crunchy or smooth?",
		"If money were no object, what car would you buy?",
		"Favourite song to sing in the shower?",
		"Who makes the best margarita?",
		"What book should every man/woman read?",
		"You ever wonder if Dr. Seuss was high when he wrote?",
		"All-time favourite muppet?",
		"What was the last time you drunk dialed?",
		"What web site can you not live without?",
		"Who's your favourite TV chef?",
		"What's the capital of Canada? (btw, it's Ottawa)",
		"What super power would you most like to have?",
		"If you ran your company who would you hire first?",
		"If you could come back as a female singer, who would you be?",
		"Name 3 things every guy has in his refrigerator?",
		"Ever taken your mom to a party and she loved it?",
		"Ever stayed in a place you thought was haunted?",
		"What are you going to name your first child?",
		"Best fast food place ever?",
		"If the police would let you shoot 3 people in the leg, who would you shoot first?",
		"You favourite Halloween costume of all time?",
		"Have you ever put a Chinese cookie fortune on your mirror?",
		"Favourite birthday party of all time?",
		"What's your favourite supermarket?",
		"What's your favourite guilty pleasure song?",
		"Scariest movie you've ever seen?",
		"What was the last time you actually bought a CD?",
		"What celebrity do people say you remind them of?",
		"What's your favourite knock-knock joke?",
		"What's the greatest cereal ever made?",
		"Have you ever been in a food fight?",
		"Have you ever taken a picture in one of those little photo booths?",
		"Best place for Christmas shopping?",
		"Have you ever wanted to hang out with Hugh Hefner for a whole day?",
		"Have you ever watched a TV show and thought you could be good friends with one of the stars?",
		"Worst person you kissed in high school?",
		"Favourite thing you ever did with your grandmother or grandfather?",
		"Your favourite pet that you've ever had?",
		"Who has the best job at your place of work?",
		"If you were given a lifetime gift certificate, what store would you choose?",
		"If you could put a plague on an ex, what plague would you give them?",
		"What movie can still make you get the tissue paper out?",
		"If you could be paid to do anything, what would you do?",
		"Your company says you can live anywhere you want and keep your job...where would you live?",
		"It's 1 in the morning and you open your fridge...what would you see that makes you really happy?"
	};
	
}
